"""Regex patterns and helpers for entml invoke/parameter parsing."""
from __future__ import annotations

from ..entml_schema.mangled import (
    mangled_json_param_tail_in_progress,
    split_mangled_json_param_tail,
)
from .invoke import (
    entml_invoke_open_is_actionable,
    entml_invoke_open_may_be_streaming,
    find_actionable_entml_invoke_open,
    is_placeholder_invoke_name,
    iter_actionable_entml_invoke_blocks,
    resolve_known_tool_names,
)
from .params import (
    extract_attr_value,
    extract_parameter_type_attr,
    find_valid_parameter_close,
    inside_parameter_value,
    invoke_structural_gap_text,
    invoke_structural_gaps,
    normalize_entml_name,
    parameter_block_spans,
    parameter_close_at,
    parameter_value_spans,
    parse_sub_tags,
    strip_actionable_entml_invoke_blocks,
    synthetic_close_invoke_body,
)
from .regex import (
    BARE_INVOKE_CHILD_OPEN_RE,
    BARE_INVOKE_CHILD_RE,
    BLOCK_RE,
    INVOKE_DIRECT_CHILD_OPEN_RE,
    INVOKE_DIRECT_CHILD_RE,
    INVOKE_DIRECT_CHILD_SKIP,
    INVOKE_RE,
    PARAM_CLOSE_BARE,
    PARAM_CLOSE_ENTML,
    PARAM_OPEN_PATTERN,
    PARAM_RE,
    PARAMETERS_RE,
    SUB_TAG_RE,
    _INVOKE_CLOSE,
    _INVOKE_OPEN_PREFIX,
    _PARAM_CLOSE_VALID_RE,
    _PARAM_CLOSE_VALID_STREAM_RE,
)
from .strip import strip_legacy_function_calls_wrapper, strip_tool_entml_residue

__all__ = [
    "BARE_INVOKE_CHILD_OPEN_RE",
    "BARE_INVOKE_CHILD_RE",
    "BLOCK_RE",
    "INVOKE_DIRECT_CHILD_OPEN_RE",
    "INVOKE_DIRECT_CHILD_RE",
    "INVOKE_DIRECT_CHILD_SKIP",
    "INVOKE_RE",
    "PARAM_CLOSE_BARE",
    "PARAM_CLOSE_ENTML",
    "PARAM_OPEN_PATTERN",
    "PARAM_RE",
    "PARAMETERS_RE",
    "SUB_TAG_RE",
    "_INVOKE_CLOSE",
    "_INVOKE_OPEN_PREFIX",
    "_PARAM_CLOSE_VALID_RE",
    "_PARAM_CLOSE_VALID_STREAM_RE",
    "entml_invoke_open_is_actionable",
    "entml_invoke_open_may_be_streaming",
    "extract_attr_value",
    "extract_parameter_type_attr",
    "find_actionable_entml_invoke_open",
    "find_valid_parameter_close",
    "inside_parameter_value",
    "invoke_structural_gap_text",
    "invoke_structural_gaps",
    "is_placeholder_invoke_name",
    "iter_actionable_entml_invoke_blocks",
    "mangled_json_param_tail_in_progress",
    "normalize_entml_name",
    "parameter_block_spans",
    "parameter_close_at",
    "parameter_value_spans",
    "parse_sub_tags",
    "resolve_known_tool_names",
    "split_mangled_json_param_tail",
    "strip_actionable_entml_invoke_blocks",
    "strip_legacy_function_calls_wrapper",
    "strip_tool_entml_residue",
    "synthetic_close_invoke_body",
]
