from __future__ import annotations

"""echotools：通用基础设施 SDK。

完全项目无关，支持调用链，覆盖 Python 3.8-3.14。
"""

import importlib
from typing import Any

from echotools._version import get_version
from echotools.sdk import EchoTools

__version__ = get_version()

__all__ = [
    "__version__",
    "EchoTools",
    "ConfigBase",
    "ConfigCenter",
    "LoggerManager",
    "get_logger",
    "set_color",
    "configure",
    "Event",
    "EventBus",
    "Tracer",
    "Trace",
    "Span",
    "get_current_trace_id",
    "set_current_trace_id",
    "get_current_span_id",
    "set_current_span_id",
    "get_request_id",
    "set_request_id",
    "ListCache",
    "MemoryCache",
    "TaskCandidate",
    "make_id",
    "AdaptiveSelector",
    "TaskDispatcher",
    "TaskScheduler",
    "ProxySelector",
    "ProxyRecord",
    "Plugin",
    "PluginRegistry",
    "discover_plugins",
    "ToolProtocol",
    "register_protocol",
    "get_protocol_by_id",
    "get_protocol",
    "list_protocols",
    "LifecycleManager",
    "AutoUpdater",
    "ProxyManager",
    "PortReleaseResult",
    "ensure_port_available",
    "RuntimeCollector",
    "WebApplication",
    "json_body",
    "safe_flush",
    "FileUtil",
    "uuid7",
    "short_id",
    "trace_id",
    "span_id",
    "atomic_write_text",
    "ensure_directory",
    "read_text_if_exists",
    "retry_with_backoff",
    "retry_on_empty",
    "retry_on_exception",
    "retry_async_generator",
    "KeyState",
    "KeyPool",
    "extract_text_from_messages",
    "split_text_chunks",
    "format_translation_response",
    "TerminalSession",
    "TerminalCallback",
    "LocalTerminal",
    "SSHTerminal",
    "PrintStream",
    "print_stream",
    "start_print_stream",
    "stop_print_stream",
    "flush_print_stream",
    "get_buffer_size",
    "get_queue_length",
    "is_print_stream_running",
    "set_print_speed",
    "configure_print_stream",
    "inject_fncall",
    "FncallStreamParser",
    "detect_tool_loop",
    "LoopDetectionResult",
    "EchoError",
    "ConfigError",
    "ValidationError",
    "NetworkError",
    "TimeoutError",
    "NotSupportedError",
    "NoCandidateError",
    "PluginError",
    "ProtocolError",
    "classify_http_error",
    "Spinner",
]

_EXPORTS: dict[str, tuple[str, str]] = {
    "ConfigBase": ("echotools.config", "ConfigBase"),
    "ConfigCenter": ("echotools.config", "ConfigCenter"),
    "LoggerManager": ("echotools.logger", "LoggerManager"),
    "get_logger": ("echotools.logger", "get_logger"),
    "set_color": ("echotools.logger", "set_color"),
    "configure": ("echotools.logger", "configure"),
    "Event": ("echotools.events", "Event"),
    "EventBus": ("echotools.events", "EventBus"),
    "Tracer": ("echotools.tracing", "Tracer"),
    "Trace": ("echotools.tracing", "Trace"),
    "Span": ("echotools.tracing", "Span"),
    "get_current_trace_id": ("echotools.tracing", "get_current_trace_id"),
    "set_current_trace_id": ("echotools.tracing", "set_current_trace_id"),
    "get_current_span_id": ("echotools.tracing", "get_current_span_id"),
    "set_current_span_id": ("echotools.tracing", "set_current_span_id"),
    "get_request_id": ("echotools.tracing", "get_request_id"),
    "set_request_id": ("echotools.tracing", "set_request_id"),
    "ListCache": ("echotools.cache", "ListCache"),
    "MemoryCache": ("echotools.cache", "MemoryCache"),
    "TaskCandidate": ("echotools.dispatch", "TaskCandidate"),
    "make_id": ("echotools.dispatch", "make_id"),
    "AdaptiveSelector": ("echotools.dispatch", "AdaptiveSelector"),
    "TaskDispatcher": ("echotools.dispatch", "TaskDispatcher"),
    "TaskScheduler": ("echotools.scheduler", "TaskScheduler"),
    "ProxySelector": ("echotools.dispatch", "ProxySelector"),
    "ProxyRecord": ("echotools.dispatch", "ProxyRecord"),
    "Plugin": ("echotools.plugin", "Plugin"),
    "PluginRegistry": ("echotools.plugin", "PluginRegistry"),
    "discover_plugins": ("echotools.plugin", "discover_plugins"),
    "ToolProtocol": ("echotools.protocol.base", "ToolProtocol"),
    "register_protocol": ("echotools.protocol.base", "register_protocol"),
    "get_protocol_by_id": ("echotools.protocol.base", "get_protocol_by_id"),
    "get_protocol": ("echotools.fncall.registry", "get_protocol"),
    "list_protocols": ("echotools.fncall.registry", "list_protocols"),
    "LifecycleManager": ("echotools.lifecycle", "LifecycleManager"),
    "AutoUpdater": ("echotools.lifecycle", "AutoUpdater"),
    "ProxyManager": ("echotools.proxy", "ProxyManager"),
    "PortReleaseResult": ("echotools.process", "PortReleaseResult"),
    "ensure_port_available": ("echotools.process", "ensure_port_available"),
    "RuntimeCollector": ("echotools.runtime", "RuntimeCollector"),
    "WebApplication": ("echotools.web.application", "WebApplication"),
    "json_body": ("echotools.web.utils", "json_body"),
    "safe_flush": ("echotools.web.utils", "safe_flush"),
    "FileUtil": ("echotools.files", "FileUtil"),
    "uuid7": ("echotools.ids", "uuid7"),
    "short_id": ("echotools.ids", "short_id"),
    "trace_id": ("echotools.ids", "trace_id"),
    "span_id": ("echotools.ids", "span_id"),
    "atomic_write_text": ("echotools.io", "atomic_write_text"),
    "ensure_directory": ("echotools.io", "ensure_directory"),
    "read_text_if_exists": ("echotools.io", "read_text_if_exists"),
    "retry_with_backoff": ("echotools.retry", "retry_with_backoff"),
    "retry_on_empty": ("echotools.retry", "retry_on_empty"),
    "retry_on_exception": ("echotools.retry", "retry_on_exception"),
    "retry_async_generator": ("echotools.retry", "retry_async_generator"),
    "KeyState": ("echotools.keys", "KeyState"),
    "KeyPool": ("echotools.keys", "KeyPool"),
    "extract_text_from_messages": ("echotools.translate", "extract_text_from_messages"),
    "split_text_chunks": ("echotools.translate", "split_text_chunks"),
    "format_translation_response": ("echotools.translate", "format_translation_response"),
    "TerminalSession": ("echotools.terminal.session", "TerminalSession"),
    "TerminalCallback": ("echotools.terminal.session", "TerminalCallback"),
    "LocalTerminal": ("echotools.terminal.local", "LocalTerminal"),
    "SSHTerminal": ("echotools.terminal.ssh", "SSHTerminal"),
    "PrintStream": ("echotools.io.printstream", "PrintStream"),
    "print_stream": ("echotools.io.printstream", "print_stream"),
    "start_print_stream": ("echotools.io.printstream", "start_print_stream"),
    "stop_print_stream": ("echotools.io.printstream", "stop_print_stream"),
    "flush_print_stream": ("echotools.io.printstream", "flush_print_stream"),
    "get_buffer_size": ("echotools.io.printstream", "get_buffer_size"),
    "get_queue_length": ("echotools.io.printstream", "get_queue_length"),
    "is_print_stream_running": ("echotools.io.printstream", "is_print_stream_running"),
    "set_print_speed": ("echotools.io.printstream", "set_print_speed"),
    "configure_print_stream": ("echotools.io.printstream", "configure_print_stream"),
    "inject_fncall": ("echotools.fncall.prompt.inject", "inject_fncall"),
    "FncallStreamParser": ("echotools.fncall.parsers.stream", "FncallStreamParser"),
    "detect_tool_loop": ("echotools.fncall.shared.loop_detect", "detect_tool_loop"),
    "LoopDetectionResult": ("echotools.fncall.shared.loop_detect", "LoopDetectionResult"),
    "EchoError": ("echotools.errors", "EchoError"),
    "ConfigError": ("echotools.errors", "ConfigError"),
    "ValidationError": ("echotools.errors", "ValidationError"),
    "NetworkError": ("echotools.errors", "NetworkError"),
    "TimeoutError": ("echotools.errors", "TimeoutError"),
    "NotSupportedError": ("echotools.errors", "NotSupportedError"),
    "NoCandidateError": ("echotools.errors", "NoCandidateError"),
    "PluginError": ("echotools.errors", "PluginError"),
    "ProtocolError": ("echotools.errors", "ProtocolError"),
    "classify_http_error": ("echotools.errors", "classify_http_error"),
    "Spinner": ("echotools.spinner", "Spinner"),
}


def __getattr__(name: str) -> Any:
    if name in _EXPORTS:
        module_path, attr = _EXPORTS[name]
        module = importlib.import_module(module_path)
        return getattr(module, attr)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")


def __dir__() -> list[str]:
    return sorted(__all__)
